name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create Project & Inject Code
        run: |
          # ساخت ساختار کامل اندروید
          flutter create --org com.ilia.goldbot --project-name goldbot my_app
          cd my_app
          flutter pub add http

          # فعال کردن دسترسی به اینترنت در اندروید
          sed -i '/<application/i \    <uses-permission android:name="android.permission.INTERNET"\/>' android/app/src/main/AndroidManifest.xml

          # انتقال کد برنامه به پروژه
          cp ../lib/main.dart lib/main.dart

          # ساخت فایل نصبی APK
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Goldbot-Release-APK
          path: my_app/build/app/outputs/flutter-apk/app-release.apk
